export const DEFAULT_PURCHASE_PRICE = 750000;
export const DEFAULT_DOWN_PAYMENT_PERCENT = 20;
export const DEFAULT_MORTGAGE_RATE_PERCENT = 6.0;
export const DEFAULT_MORTGAGE_TERM_YEARS = 30;
export const DEFAULT_MONTHLY_RENT = 3500;
export const DEFAULT_INVESTMENT_RETURN_PERCENT = 7.0;
export const DEFAULT_HOME_APPRECIATION_PERCENT = 3.0;
export const DEFAULT_ANALYSIS_PERIOD_YEARS = 10;

// Fixed assumptions
export const PROPERTY_TAX_INSURANCE_MAINTENANCE_PERCENT = 1.5;
export const RENT_GROWTH_PERCENT = 3.0;
export const PURCHASE_CLOSING_COSTS_PERCENT = 2.0;
export const SELLING_CLOSING_COSTS_PERCENT = 6.0; 